AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy Secrets Service using Docker on EC2"

Parameters:
  KeyPairName:
    Type: String
    Description: Name of the EC2 Key Pair for SSH access

  JWTSecret:
    Type: String
    Description: JWT Secret for authentication
    NoEcho: true

  AuthUsername:
    Type: String
    Description: Basic auth username

  AuthPassword:
    Type: String
    Description: Basic auth password
    NoEcho: true

  AllowedOrigins:
    Type: String
    Description: Allowed CORS origins
    Default: "*"

  OpenAIAPIKey:
    Type: String
    Description: OpenAI API Key
    NoEcho: true
    Default: ""

  FirebaseAPIKey:
    Type: String
    Description: Firebase API Key
    NoEcho: true
    Default: ""

  GitHubRepo:
    Type: String
    Description: GitHub repository URL

  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

Resources:
  # Security Group
  SecretsServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Secrets Service
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH access
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
          Description: Application port
      Tags:
        - Key: Name
          Value: secrets-service-sg

  # IAM Role for EC2
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: SecretsServicePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: "*"

  # Instance Profile
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  # EC2 Instance
  SecretsServiceInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2 AMI (update as needed)
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref SecretsServiceSecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y

          # Install Docker
          yum install -y docker git
          systemctl start docker
          systemctl enable docker
          usermod -a -G docker ec2-user

          # Install Docker Compose
          curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

          # Install AWS CLI v2
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install

          # Create application directory
          mkdir -p /opt/secrets-service
          cd /opt/secrets-service

          # Clone repository
          git clone ${GitHubRepo} .
          cd backend

          # Create environment file
          cat > .env << EOF
          VAULT_ADDR=http://localhost:8200
          VAULT_TOKEN=dev-token
          JWT_SECRET=${JWTSecret}
          PORT=8080
          ALLOWED_ORIGIN=${AllowedOrigins}
          VITE_SECRETS_SERVICE_USERNAME=${AuthUsername}
          VITE_SECRETS_SERVICE_PASSWORD=${AuthPassword}
          OPENAI_API_KEY=${OpenAIAPIKey}
          FIREBASE_API_KEY=${FirebaseAPIKey}
          EOF

          # Create management scripts
          cat > /opt/secrets-service/start.sh << 'EOF'
          #!/bin/bash
          cd /opt/secrets-service/backend
          docker-compose up -d
          EOF

          cat > /opt/secrets-service/stop.sh << 'EOF'
          #!/bin/bash
          cd /opt/secrets-service/backend
          docker-compose down
          EOF

          cat > /opt/secrets-service/restart.sh << 'EOF'
          #!/bin/bash
          cd /opt/secrets-service/backend
          docker-compose down
          git pull origin main
          docker-compose up -d --build
          EOF

          cat > /opt/secrets-service/status.sh << 'EOF'
          #!/bin/bash
          cd /opt/secrets-service/backend
          docker-compose ps
          EOF

          cat > /opt/secrets-service/logs.sh << 'EOF'
          #!/bin/bash
          cd /opt/secrets-service/backend
          docker-compose logs -f
          EOF

          # Make scripts executable
          chmod +x /opt/secrets-service/*.sh

          # Start the application
          /opt/secrets-service/start.sh

          # Create systemd service for auto-restart
          cat > /etc/systemd/system/secrets-service.service << 'EOF'
          [Unit]
          Description=Secrets Service
          Requires=docker.service
          After=docker.service

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/opt/secrets-service/start.sh
          ExecStop=/opt/secrets-service/stop.sh

          [Install]
          WantedBy=multi-user.target
          EOF

          systemctl enable secrets-service
          systemctl start secrets-service

      Tags:
        - Key: Name
          Value: secrets-service-instance

Outputs:
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt SecretsServiceInstance.PublicIp
    Export:
      Name: !Sub "${AWS::StackName}-PublicIP"

  ApplicationURL:
    Description: URL of the application
    Value: !Sub "http://${SecretsServiceInstance.PublicIp}:8080"
    Export:
      Name: !Sub "${AWS::StackName}-ApplicationURL"

  SSHCommand:
    Description: SSH command to connect to the instance
    Value: !Sub "ssh -i ${KeyPairName}.pem ec2-user@${SecretsServiceInstance.PublicIp}"
    Export:
      Name: !Sub "${AWS::StackName}-SSHCommand"
