version: "3.8"

# Development override for docker-compose
# This file provides development-specific configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  secrets-service:
    # Mount source code for development
    volumes:
      - .:/app
      - /app/bin # Exclude binary directory from mount
    # Enable hot reload in development
    environment:
      - GO_ENV=development
    # Override build context for development
    build:
      context: .
      dockerfile: dockerfile
      target: builder # Use builder stage for development

  nginx:
    # Mount nginx config for easy editing
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
      - ./logs/nginx:/var/log/nginx
    # Development-specific nginx configuration
    environment:
      - NGINX_DEBUG=1
    # Override for development
    ports:
      - "8080:80" # Map to 8080 for development to avoid conflicts
      - "8443:443" # Map to 8443 for development

  # Optional: Add a development database or other services
  # vault:
  #   image: vault:latest
  #   cap_add:
  #     - IPC_LOCK
  #   environment:
  #     - VAULT_DEV_ROOT_TOKEN_ID=dev-token
  #     - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
  #   ports:
  #     - "8200:8200"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
