version: "3.8"

services:
  secrets-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
